document.querySelector(".defPage").classList.add("active")
document.querySelector(".blog").setAttribute("href", "../blog/")
document.querySelector(".habitPage").setAttribute("href", "../habit/")
document.querySelector(".reminderPage").setAttribute("href", "../reminder/")
document.querySelector(".progressPage").setAttribute("href", "../progress/")
document.querySelector(".cumuPage").setAttribute("href", "../comunity/")
document.querySelector(".defPage").setAttribute("href", "index.php")
document.querySelector(".feelingsPage").setAttribute("href", "../feelings/")
