document.querySelector(".blog").classList.add("active")
document.querySelector(".blog").setAttribute("href", "../index.php")
document.querySelector(".habitPage").setAttribute("href", "../../habit/")
document.querySelector(".reminderPage").setAttribute("href", "../../reminder/")
document.querySelector(".progressPage").setAttribute("href", "../../progress/")
document.querySelector(".cumuPage").setAttribute("href", "../../comunity/")
document.querySelector(".defPage").setAttribute("href", "../../definition/")
document.querySelector(".feelingsPage").setAttribute("href", "../../feelings/")